### PR TITLE
Fix diff function

### LINKED ISSUE #14: Changing network values in storybook sometimes results in incorrect output
Described here: https://github.com/Wokstym/react-vis-graph-wrapper/pull/11#issuecomment-1030657830

### PR DESCRIPTION
**Pull request by ZachHaber**
Fixes #14
The updated diff function was incorrect
It's now correct and works with edges with IDs and edges without ids.
Note: without IDs, every time it changes, it removes the old and adds the new.

Fix issues with mutating the props!

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -140,22 +142,35 @@ const VisGraph = forwardRef<
...
+      nodes.remove(removed);
+    }
+    // Shallow clone nodes to ensure props aren't mutated!
+    if (added.length) {
+      nodes.add(shallowClone(added));
+    }
+    if (updated.length) {
+      nodes.update(shallowClone(updated));
+    }
+    prevNodes.current = nodes.get();
```
Comment (ZachHaber) [inline src/index.tsx]: I need to keep this as it was (same with prevEdges) which will work better with the isEqual calls. And I can just run `nodes.get` through the `diff` function.

Though I'm thinking it might make sense to remove the isEqual calls anyway... Since theoretically as long as the user doesn't generate the nodes/edges on the fly, it'll have changes, and if they do, as long as they have IDs, we'll more or less be doing the same thing. If they don't have IDs, then we'd be removing/adding them every time

**Comment by WikKam** [comment]
I will run it tomorrow, I have some concerns about a few things but I don't know if we wanna adress them in this mr.

**Comment by WikKam** [comment]
I will run it tomorrow, I have some concerns about a few things but I don't know if we wanna adress them in this mr.

- IMO tracking the previous values of nodes and edges should be at least done in seperate useEffect, the best solution would be to abstract pretty simple `usePreviousValue` hook.
- Two useEffects relating tracking the updated, added, deleted nodes basically do the same thing and should also be abstracted into some other custom hook

Other than that, in terms of code it is fine for me

File: src/index.tsx [hunk 2]
```diff
@@ -138,23 +140,36 @@ const VisGraph = forwardRef<
...
-    edges.remove(removed);
-    edges.add(added);
-    edges.update(updated);
+    const { added, removed, updated } = diff(edges.get(), graph.edges);
+    if (removed.length) {
+      edges.remove(removed);
+    }
+    // Shallow clone edges to ensure props aren't mutated!
+    if (added.length) {
+      edges.add(shallowClone(added));
```
Comment (WikKam) [inline src/index.tsx:168]: I would just
```
edges.add([...added])
```

File: src/index.tsx [hunk 3]
```diff
@@ -138,23 +140,36 @@ const VisGraph = forwardRef<
...
       return; // No change!
     }
-    const { added, removed, updated } = diff(prevEdges.current, graph.edges);
-
-    edges.remove(removed);
-    edges.add(added);
-    edges.update(updated);
+    const { added, removed, updated } = diff(edges.get(), graph.edges);
+    if (removed.length) {
+      edges.remove(removed);
```
Comment (WikKam) [inline src/index.tsx]: I would just
```
edges.remove([...removed])
```

File: src/index.tsx (hunk 2 above)
Comment (WikKam) [inline src/index.tsx]: same as above

File: src/index.tsx [hunk 4]
```diff
@@ -138,23 +140,36 @@ const VisGraph = forwardRef<
...
+    }
+    // Shallow clone edges to ensure props aren't mutated!
+    if (added.length) {
+      edges.add(shallowClone(added));
+    }
+    if (updated.length) {
+      edges.update(shallowClone(updated));
```
Comment (WikKam) [inline src/index.tsx]: same as above

File: src/index.tsx [hunk 5]
```diff
@@ -138,23 +140,36 @@ const VisGraph = forwardRef<
...
+    if (removed.length) {
+      nodes.remove(removed);
+    }
+    // Shallow clone nodes to ensure props aren't mutated!
+    if (added.length) {
+      nodes.add(shallowClone(added));
+    }
+    if (updated.length) {
+      nodes.update(shallowClone(updated));
+    }
```
Comment (WikKam) [inline src/index.tsx]: Same as analogical section in the update edges useEffect

File: src/index.tsx (hunk 3 above)
Comment (WikKam) [reply src/index.tsx]: And correct me if I'm wrong but the if statement seems also unnecessarry, will something happen if we call `add, update, remove` with empty array?

Comment (ZachHaber) [reply src/index.tsx]: Nothing happens if we call them with an empty array, so yeah, I can remove those if statements.
No need for `edges.remove([...removed])` as the remove function doesn't appear to mutate the inputs, plus if it's going in removed, it by definition came from the mutable `edges` source.

File: src/index.tsx (hunk 2 above)
Comment (ZachHaber) [reply src/index.tsx]: The main reason I added these if checks was to avoid a bunch of no-op function calls since they were easily avoidable.

File: src/index.tsx (hunk 3 above)
Comment (WikKam) [reply src/index.tsx]: But do we need that `shallowClone` function to copy array or is `[...array]` enough for it?

File: src/index.tsx (hunk 5 above)
Comment (ZachHaber) [reply src/index.tsx:154]: > I will run it tomorrow, I have some concerns about a few things but I don't know if we wanna adress them in this mr.
> 
> * IMO tracking the previous values of nodes and edges should be at least done in seperate useEffect, the best solution would be to abstract pretty simple `usePreviousValue` hook.
> * Two useEffects relating tracking the updated, added, deleted nodes basically do the same thing and should also be abstracted into some other custom hook
> 
> Other than that, in terms of code it is fine for me

I do see your point about setting up a custom hook to do the functionality that the edges/nodes need, I'll probably tie in the refs and other bits into that custom hook.

As for tracking the previous values of the nodes and edges, given that we are only using them here, we'd essentially be using an effect hook with the same dependencies to do that tracking, and given how small that functionality is, it's a bit wasteful in this specialized use case, especially since I need the ref to exist before this effect, but change the value of it afterwards, which unfortunately makes a `usePreviousValue` hook a bit more complicated to set up.

**Comment by ZachHaber** [comment]
> I will run it tomorrow, I have some concerns about a few things but I don't know if we wanna adress them in this mr.
> 
> * IMO tracking the previous values of nodes and edges should be at least done in seperate useEffect, the best solution would be to abstract pretty simple `usePreviousValue` hook.
> * Two useEffects relating tracking the updated, added, deleted nodes basically do the same thing and should also be abstracted into some other custom hook
> 
> Other than that, in terms of code it is fine for me

I do see your point about setting up a custom hook to do the functionality that the edges/nodes need, I'll probably tie in the refs and other bits into that custom hook.

As for tracking the previous values of the nodes and edges, given that we are only using them here, we'd essentially be using an effect hook with the same dependencies to do that tracking, and given how small that functionality is, it's a bit wasteful in this specialized use case, especially since I need the ref to exist before this effect, but change the value of it afterwards, which unfortunately makes a `usePreviousValue` hook a bit more complicated to set up.

**Comment by WikKam** [comment]
> > I will run it tomorrow, I have some concerns about a few things but I don't know if we wanna adress them in this mr.
> > 
> > * IMO tracking the previous values of nodes and edges should be at least done in seperate useEffect, the best solution would be to abstract pretty simple `usePreviousValue` hook.
> > * Two useEffects relating tracking the updated, added, deleted nodes basically do the same thing and should also be abstracted into some other custom hook
> > 
> > Other than that, in terms of code it is fine for me
> 
> I do see your point about setting up a custom hook to do the functionality that the edges/nodes need, I'll probably tie in the refs and other bits into that custom hook.
> 
> As for tracking the previous values of the nodes and edges, given that we are only using them here, we'd essentially be using an effect hook with the same dependencies to do that tracking, and given how small that functionality is, it's a bit wasteful in this specialized use case, especially since I need the ref to exist before this effect, but change the value of it afterwards, which unfortunately makes a `usePreviousValue` hook a bit more complicated to set up.

Sure, I am fine with that, lets do it in other MR. I think you are also right about the previous value, since the effects always maintain the same order

File: src/index.tsx (hunk 3 above)
Comment (ZachHaber) [reply src/index.tsx]: For everything but the remove function, yes. we need the shallowClone, because it mutates the array element objects by adding an `id` onto it if there isn't one, which goes very much against how react works, so in order to protect the users of this component, it's best to shallow clone the individual elements of the array.

**Comment by ZachHaber** [comment]
I went ahead and made a hook for it, because it was pretty straight forward.
As a side note, I just wanted to say that "MR" confused me at first as I'm used to calling them PRs. I blame localizations 😛
